name: flutta

description: Flutta - Flutter Crypto Wallet with Send All feature

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.3.0
  http: ^1.2.0
  bip39: ^1.0.4
  hex: ^0.2.0
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_animate: ^4.5.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
