name: Build Unsigned iOS IPA for Flutta

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Enable iOS
        run: flutter config --enable-ios

      - name: Get dependencies
        run: flutter pub get

      - name: Build Unsigned IPA
        run: flutter build ipa --release --no-codesign --no-tree-shake-icons

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Flutta-unsigned-ipa
          path: build/ios/ipa/*.ipa
